AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for sam-test
  
Globals:
  Function:
    Runtime: nodejs12.x
    Environment:
      Variables:
        TABLE_NAME: !Ref Table
    Timeout: 300
    MemorySize: 128

Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: "id"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST

  GetTest:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: test/
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Table
      Handler: get.lambdaHandler
      Runtime: nodejs12.x
      Events:
        GetTest:
          Type: Api
          Properties:
            Path: /test
            Method: get
  
  PutTest:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: test/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      Handler: put.lambdaHandler
      Events:
        GetTest:
          Type: Api
          Properties:
            Path: /test
            Method: put
  
  DeleteTest:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: test/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      Handler: delete.lambdaHandler
      Events:
        DeleteTest:
          Type: Api
          Properties:
            Path: /test
            Method: delete